#!/usr/bin/env bash
set -euo pipefail

PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

APPLY=0

TARGET_CONFIG="${TARGET_CONFIG:-/etc/vpn-killswitch/config.toml}"
VPN_LOCK_CONFIG="${VPN_LOCK_CONFIG:-/etc/vpn-lock/vpn-lock.conf}"
VPN_BYPASS_CONFIG="${VPN_BYPASS_CONFIG:-/etc/vpn-bypass/domains.txt}"
VPN_BYPASS_LEGACY_CONFIG="${VPN_BYPASS_LEGACY_CONFIG:-/etc/vpn-bypass-domains.txt}"

VPN_CONNECTION_NAME=""
VPN_CONNECTION_TYPES="vpn wireguard"
MANAGE_HOSTS="true"

BYPASS_DOMAINS=()
LOCK_DOMAINS=()

usage() {
  cat <<'EOF'
Usage: ./scripts/migrate-legacy-config.sh [--apply] [--target PATH]

Imports old vpn-bypass and vpn-lock config values into vpn-killswitch TOML.

Default mode is dry-run. Nothing is written unless --apply is passed.

Options:
  --apply              Write the target TOML config.
  --target PATH        Target config. Default: /etc/vpn-killswitch/config.toml.
  --vpn-lock PATH      Old vpn-lock config. Default: /etc/vpn-lock/vpn-lock.conf.
  --vpn-bypass PATH    Old vpn-bypass domains file. Default: /etc/vpn-bypass/domains.txt.
  --legacy-bypass PATH Older vpn-bypass domains file. Default: /etc/vpn-bypass-domains.txt.
  -h, --help

Environment:
  TARGET_CONFIG
  VPN_LOCK_CONFIG
  VPN_BYPASS_CONFIG
  VPN_BYPASS_LEGACY_CONFIG
EOF
}

log() {
  printf 'migrate-legacy-config: %s\n' "$*"
}

die() {
  printf 'migrate-legacy-config: %s\n' "$*" >&2
  exit 1
}

normalize_domain() {
  local domain="${1%.}"
  domain="${domain,,}"
  domain="${domain//[$'\t\r\n ']/}"
  if [ -z "$domain" ]; then
    return 1
  fi
  if [[ "$domain" == *".."* ]] || [[ ! "$domain" =~ ^[a-z0-9][a-z0-9._-]*[a-z0-9]$|^[a-z0-9]$ ]]; then
    return 1
  fi
  printf '%s\n' "$domain"
}

contains_domain() {
  local needle="$1"
  shift
  local item
  for item in "$@"; do
    if [ "$item" = "$needle" ]; then
      return 0
    fi
  done
  return 1
}

add_unique() {
  local list_name="$1"
  local raw="$2"
  local domain
  domain="$(normalize_domain "$raw" 2>/dev/null || true)"
  [ -n "$domain" ] || return 0

  if [ "$list_name" = "bypass" ]; then
    contains_domain "$domain" "${BYPASS_DOMAINS[@]:-}" && return 0
    BYPASS_DOMAINS+=("$domain")
    return 0
  fi

  contains_domain "$domain" "${LOCK_DOMAINS[@]:-}" && return 0
  LOCK_DOMAINS+=("$domain")
}

read_bypass_file() {
  local file="$1"
  local line domain
  [ -r "$file" ] || return 0
  log "read bypass domains: $file"
  while IFS= read -r line; do
    line="${line%%#*}"
    for domain in $line; do
      add_unique bypass "$domain"
    done
  done <"$file"
}

read_lock_config() {
  local file="$1"
  [ -r "$file" ] || return 0
  log "read lock config: $file"

  VPN_CONNECTION_NAME=""
  VPN_CONNECTION_TYPES="vpn wireguard"
  MANAGE_HOSTS="true"
  PROTECTED_DOMAINS=()

  # shellcheck source=/etc/vpn-lock/vpn-lock.conf
  source "$file"

  local domain
  for domain in "${PROTECTED_DOMAINS[@]:-}"; do
    domain="${domain//,/ }"
    local token
    for token in $domain; do
      add_unique lock "$token"
    done
  done
}

remove_cross_list_duplicates() {
  local next_lock=()
  local domain
  for domain in "${LOCK_DOMAINS[@]:-}"; do
    if contains_domain "$domain" "${BYPASS_DOMAINS[@]:-}"; then
      log "skip lock domain already present in bypass: $domain"
      continue
    fi
    next_lock+=("$domain")
  done
  LOCK_DOMAINS=("${next_lock[@]}")
}

toml_array() {
  local item
  local first=1
  printf '['
  for item in "$@"; do
    if [ "$first" -eq 0 ]; then
      printf ', '
    fi
    first=0
    printf '"%s"' "$item"
  done
  printf ']'
}

emit_toml() {
  cat <<EOF
# Generated by scripts/migrate-legacy-config.sh.

[vpn]
connection_name = "${VPN_CONNECTION_NAME}"
connection_types = $(toml_array ${VPN_CONNECTION_TYPES})

[bypass]
domains = $(toml_array "${BYPASS_DOMAINS[@]:-}")
state_path = "/run/vpn-killswitch/bypass-routes.v4"

[killswitch]
domains = $(toml_array "${LOCK_DOMAINS[@]:-}")
manage_hosts = ${MANAGE_HOSTS}
hosts_file = "/etc/hosts"
nft_table_name = "vpn_killswitch_lock"
state_dir = "/var/lib/vpn-killswitch"
run_dir = "/run/vpn-killswitch"
EOF
}

write_target() {
  local tmp dir
  dir="$(dirname "$TARGET_CONFIG")"
  if [ "$APPLY" -ne 1 ]; then
    log "DRY-RUN write target: $TARGET_CONFIG"
    emit_toml
    return 0
  fi
  if [ "$(id -u)" -ne 0 ] && [[ "$TARGET_CONFIG" = /etc/* ]]; then
    die "run with sudo to write $TARGET_CONFIG"
  fi
  mkdir -p "$dir"
  tmp="$(mktemp "${dir%/}/.config.XXXXXX")"
  emit_toml >"$tmp"
  chmod 0644 "$tmp"
  mv "$tmp" "$TARGET_CONFIG"
  log "wrote $TARGET_CONFIG"
}

parse_args() {
  while [ "$#" -gt 0 ]; do
    case "$1" in
      --apply)
        APPLY=1
        shift
        ;;
      --target)
        [ "$#" -ge 2 ] || die "--target requires a value"
        TARGET_CONFIG="$2"
        shift 2
        ;;
      --vpn-lock)
        [ "$#" -ge 2 ] || die "--vpn-lock requires a value"
        VPN_LOCK_CONFIG="$2"
        shift 2
        ;;
      --vpn-bypass)
        [ "$#" -ge 2 ] || die "--vpn-bypass requires a value"
        VPN_BYPASS_CONFIG="$2"
        shift 2
        ;;
      --legacy-bypass)
        [ "$#" -ge 2 ] || die "--legacy-bypass requires a value"
        VPN_BYPASS_LEGACY_CONFIG="$2"
        shift 2
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        die "unknown option: $1"
        ;;
    esac
  done
}

main() {
  parse_args "$@"
  read_bypass_file "$VPN_BYPASS_CONFIG"
  read_bypass_file "$VPN_BYPASS_LEGACY_CONFIG"
  read_lock_config "$VPN_LOCK_CONFIG"
  remove_cross_list_duplicates
  write_target
}

main "$@"
